// GENERATED by scripts/generate-druid-sql-docs.mjs from Apache Druid 37.0.0 docs (Apache-2.0).
// Do not edit by hand — re-run `yarn generate:sql-docs`.
/* eslint-disable */
export const DRUID_DOCS_VERSION = '37.0.0'; // = DRUID_VERSION from .env at generation time

export interface SqlFunctionDoc {
  args: string;
  description: string;
}

export interface SqlDataTypeDoc {
  runtime: string;
  description: string;
}

export const SQL_FUNCTIONS: Record<string, SqlFunctionDoc> = {
  "ABS": {
    "args": "expr",
    "description": "Absolute value."
  },
  "ACOS": {
    "args": "expr",
    "description": "Arc cosine of `expr`."
  },
  "ANY_VALUE": {
    "args": "expr, [maxBytesPerValue, [aggregateMultipleValues]]",
    "description": "Returns any value of `expr` including null. This aggregator can simplify and optimize the performance by returning the first encountered value (including `null`).\n\nIf `expr` is a string or complex type `maxBytesPerValue` amount of space is allocated for the aggregation. Strings longer than this limit are truncated. The `maxBytesPerValue` parameter should be set as low as possible, since high values will lead to wasted memory.\nIf `maxBytesPerValue` is omitted; it defaults to `1024`. `aggregateMultipleValues` is an optional boolean flag controls the behavior of aggregating a multi-value dimension. `aggregateMultipleValues` is set as true by default and returns the stringified array in case of a multi-value dimension. By setting it to false, function will return first value instead."
  },
  "APPROX_COUNT_DISTINCT": {
    "args": "expr",
    "description": "Counts distinct values of `expr` using an approximate algorithm. The `expr` can be a regular column or a prebuilt sketch column.\n\nThe specific algorithm depends on the value of `druid.sql.approxCountDistinct.function`. By default, this is `APPROX_COUNT_DISTINCT_BUILTIN`. If the DataSketches extension is loaded, you can set it to `APPROX_COUNT_DISTINCT_DS_HLL` or `APPROX_COUNT_DISTINCT_DS_THETA`.\n\nWhen run on prebuilt sketch columns, the sketch column type must match the implementation of this function. For example: when `druid.sql.approxCountDistinct.function` is set to `APPROX_COUNT_DISTINCT_BUILTIN`, this function runs on prebuilt hyperUnique columns, but not on prebuilt HLLSketchBuild columns."
  },
  "APPROX_COUNT_DISTINCT_BUILTIN": {
    "args": "expr",
    "description": "_Usage note:_ consider using `APPROX_COUNT_DISTINCT_DS_HLL` instead, which offers better accuracy in many cases.\n\nCounts distinct values of `expr` using Druid's built-in \"cardinality\" or \"hyperUnique\" aggregators, which implement a variant of HyperLogLog. The `expr` can be a string, a number, or a prebuilt hyperUnique column. Results are always approximate, regardless of the value of `useApproximateCountDistinct`."
  },
  "APPROX_COUNT_DISTINCT_DS_HLL": {
    "args": "expr, [lgK, tgtHllType]",
    "description": "Counts distinct values of `expr`, which can be a regular column or an HLL sketch column. Results are always approximate, regardless of the value of `useApproximateCountDistinct`. The `lgK` and `tgtHllType` parameters here are, like the equivalents in the aggregator, described in the HLL sketch documentation. See also `COUNT(DISTINCT expr)`."
  },
  "APPROX_COUNT_DISTINCT_DS_THETA": {
    "args": "expr, [size]",
    "description": "Counts distinct values of `expr`, which can be a regular column or a Theta sketch column. Results are always approximate, regardless of the value of `useApproximateCountDistinct`. The `size` parameter is described in the Theta sketch documentation. See also `COUNT(DISTINCT expr)`."
  },
  "APPROX_QUANTILE": {
    "args": "expr, probability, [resolution]",
    "description": "_Deprecated._ Use `APPROX_QUANTILE_DS` instead, which provides a superior distribution-independent algorithm with formal error guarantees.\n\nComputes approximate quantiles on numeric or approxHistogram expressions. `probability` should be between 0 and 1, exclusive. `resolution` is the number of centroids to use for the computation. Higher resolutions will give more precise results but also have higher overhead. If not provided, the default resolution is 50. Load the approximate histogram extension to use this function."
  },
  "APPROX_QUANTILE_DS": {
    "args": "expr, probability, [k]",
    "description": "Computes approximate quantiles on numeric or Quantiles sketch expressions. The `probability` value should be between 0 and 1, exclusive. The `k` parameter is described in the Quantiles sketch documentation.\n\nSee the known issue with this function."
  },
  "APPROX_QUANTILE_FIXED_BUCKETS": {
    "args": "expr, probability, numBuckets, lowerLimit, upperLimit, [outlierHandlingMode]",
    "description": "Computes approximate quantiles on numeric or fixed buckets histogram expressions. `probability` should be between 0 and 1, exclusive. The `numBuckets`, `lowerLimit`, `upperLimit`, and `outlierHandlingMode` parameters are described in the fixed buckets histogram documentation. Load the approximate histogram extension to use this function."
  },
  "ARRAY_AGG": {
    "args": "[DISTINCT] expr, [size]",
    "description": "Collects all values of the specified expression into an array. To include only unique values, specify `DISTINCT`. `size` determines the maximum aggregation size in bytes and defaults to 1024 bytes. If the resulting array exceeds the size limit, the query fails. `ORDER BY` is not supported. The order of elements in the output array may vary depending on the processing order."
  },
  "ARRAY_APPEND": {
    "args": "arr, expr",
    "description": "Appends the expression to the array. The source array type determines the resulting array type."
  },
  "ARRAY_CONCAT": {
    "args": "arr1, arr2",
    "description": "Concatenates two arrays. The type of `arr1` determines the resulting array type."
  },
  "ARRAY_CONCAT_AGG": {
    "args": "[DISTINCT] expr, [size]",
    "description": "Concatenates array inputs into a single array. To include only unique values, specify `DISTINCT`. `expr` must be an array. `size` determines the maximum aggregation size in bytes and defaults to 1024 bytes. If the resulting array exceeds the size limit, the query fails. Druid ignores null array expressions, but null values within arrays are included in the output. `ORDER BY` is not supported. The order of elements in the output array may vary depending on the processing order."
  },
  "ARRAY_CONTAINS": {
    "args": "arr, expr",
    "description": "Checks if the array contains the specified expression. If the specified expression is a scalar value, returns true if the source array contains the value. If the specified expression is an array, returns true if the source array contains all elements of the expression."
  },
  "ARRAY_LENGTH": {
    "args": "arr",
    "description": "Returns the length of the array."
  },
  "ARRAY_OFFSET": {
    "args": "arr, long",
    "description": "Returns the array element at the specified zero-based index. Returns null if the index is out of bounds."
  },
  "ARRAY_OFFSET_OF": {
    "args": "arr, expr",
    "description": "Returns the 0-based index of the first occurrence of `expr` in the array. If no matching elements exist in the array, returns `null`."
  },
  "ARRAY_ORDINAL": {
    "args": "arr, long",
    "description": "Returns the array element at the specified one-based index. Returns null if the index is out of bounds."
  },
  "ARRAY_ORDINAL_OF": {
    "args": "arr, expr",
    "description": "Returns the 1-based index of the first occurrence of `expr` in the array. If no matching elements exist in the array, returns `null`."
  },
  "ARRAY_OVERLAP": {
    "args": "arr1, arr2",
    "description": "Returns true if two arrays have any elements in common. Treats `NULL` values as known elements."
  },
  "ARRAY_PREPEND": {
    "args": "expr, arr",
    "description": "Prepends the expression to the array. The source array type determines the resulting array type."
  },
  "ARRAY_SLICE": {
    "args": "arr, start, end",
    "description": "Returns a subset of the array from the zero-based index `start` (inclusive) to `end` (exclusive). Returns null if `start` is less than 0, greater than the length of the array, or greater than `end`."
  },
  "ARRAY_TO_MV": {
    "args": "arr",
    "description": "Converts an array of any type into a multi-value string."
  },
  "ARRAY_TO_STRING": {
    "args": "arr, delimiter",
    "description": "Joins all elements of the array into a string using the specified delimiter."
  },
  "ASIN": {
    "args": "expr",
    "description": "Arc sine of `expr`."
  },
  "ATAN": {
    "args": "expr",
    "description": "Arc tangent of `expr`."
  },
  "ATAN2": {
    "args": "y, x",
    "description": "Angle theta from the conversion of rectangular coordinates (x, y) to polar * coordinates (r, theta)."
  },
  "AVG": {
    "args": "expr",
    "description": "Averages numbers."
  },
  "BIT_AND": {
    "args": "expr",
    "description": "Performs a bitwise AND operation on all input values."
  },
  "BIT_OR": {
    "args": "expr",
    "description": "Performs a bitwise OR operation on all input values."
  },
  "BIT_XOR": {
    "args": "expr",
    "description": "Performs a bitwise XOR operation on all input values."
  },
  "BITWISE_AND": {
    "args": "expr1, expr2",
    "description": "Returns the result of `expr1 & expr2`. Double values will be implicitly cast to longs, use `BITWISE_CONVERT_DOUBLE_TO_LONG_BITS` to perform bitwise operations directly with doubles."
  },
  "BITWISE_COMPLEMENT": {
    "args": "expr",
    "description": "Returns the result of `~expr`. Double values will be implicitly cast to longs, use `BITWISE_CONVERT_DOUBLE_TO_LONG_BITS` to perform bitwise operations directly with doubles."
  },
  "BITWISE_CONVERT_DOUBLE_TO_LONG_BITS": {
    "args": "expr",
    "description": "Converts the bits of an IEEE 754 floating-point double value to a long. If the input is not a double, it is implicitly cast to a double prior to conversion."
  },
  "BITWISE_CONVERT_LONG_BITS_TO_DOUBLE": {
    "args": "expr",
    "description": "Converts a long to the IEEE 754 floating-point double specified by the bits stored in the long. If the input is not a long, it is implicitly cast to a long prior to conversion."
  },
  "BITWISE_OR": {
    "args": "expr1, expr2",
    "description": "Returns the result of `expr1 [PIPE] expr2`. Double values will be implicitly cast to longs, use `BITWISE_CONVERT_DOUBLE_TO_LONG_BITS` to perform bitwise operations directly with doubles."
  },
  "BITWISE_SHIFT_LEFT": {
    "args": "expr1, expr2",
    "description": "Returns the result of `expr1 << expr2`. Double values will be implicitly cast to longs, use `BITWISE_CONVERT_DOUBLE_TO_LONG_BITS` to perform bitwise operations directly with doubles."
  },
  "BITWISE_SHIFT_RIGHT": {
    "args": "expr1, expr2",
    "description": "Returns the result of `expr1 >> expr2`. Double values will be implicitly cast to longs, use `BITWISE_CONVERT_DOUBLE_TO_LONG_BITS` to perform bitwise operations directly with doubles."
  },
  "BITWISE_XOR": {
    "args": "expr1, expr2",
    "description": "Returns the result of `expr1 ^ expr2`. Double values will be implicitly cast to longs, use `BITWISE_CONVERT_DOUBLE_TO_LONG_BITS` to perform bitwise operations directly with doubles."
  },
  "BLOOM_FILTER": {
    "args": "expr, numEntries",
    "description": "Computes a bloom filter from values produced by `expr`, with `numEntries` maximum number of distinct values before false positive rate increases. See bloom filter extension documentation for additional details."
  },
  "BLOOM_FILTER_TEST": {
    "args": "expr, serialized-filter",
    "description": "Returns true if the value of `expr` is contained in the base64-serialized Bloom filter. See the Bloom filter extension documentation for additional details. See the `BLOOM_FILTER` function for computing Bloom filters."
  },
  "BTRIM": {
    "args": "expr[, chars]",
    "description": "Alternate form of `TRIM(BOTH chars FROM expr)`."
  },
  "CAST": {
    "args": "value AS TYPE",
    "description": "Cast value to another type. See Data types for details about how Druid SQL handles CAST."
  },
  "CEIL": {
    "args": "timestamp_expr TO unit",
    "description": "Rounds up a timestamp, returning it as a new timestamp. The `unit` parameter must be unquoted and can be SECOND, MINUTE, HOUR, DAY, WEEK, MONTH, QUARTER, or YEAR."
  },
  "CHAR_LENGTH": {
    "args": "expr",
    "description": "Alias for `LENGTH`."
  },
  "CHARACTER_LENGTH": {
    "args": "expr",
    "description": "Alias for `LENGTH`."
  },
  "COALESCE": {
    "args": "value1, value2, ...",
    "description": "Returns the first non-null value."
  },
  "CONCAT": {
    "args": "expr[, expr, ...]",
    "description": "Concatenates a list of expressions. Also see the concatenation operator."
  },
  "CONTAINS_STRING": {
    "args": "expr, str",
    "description": "Returns true if the `str` is a substring of `expr`."
  },
  "COS": {
    "args": "expr",
    "description": "Trigonometric cosine of an angle `expr`."
  },
  "COT": {
    "args": "expr",
    "description": "Trigonometric cotangent of an angle `expr`."
  },
  "COUNT": {
    "args": "[DISTINCT] expr",
    "description": "Counts the values of `expr`.\n\nBy default, using DISTINCT serves as an alias for `APPROX_COUNT_DISTINCT` (`useApproximateCountDistinct=true`). The specific algorithm depends on the value of `druid.sql.approxCountDistinct.function`. In this mode, you can use strings, numbers, or prebuilt sketches. If counting prebuilt sketches, the prebuilt sketch type must match the selected algorithm.\n\nWhen `useApproximateCountDistinct=false`, returns the exact computation. In this case, `expr` must be string or numeric, since exact counts are not possible using prebuilt sketches. In exact mode, only one distinct count per query is permitted unless `useGroupingSetForExactDistinct` is enabled.\n\nCounts each distinct value in a `multi-value`-row separately."
  },
  "CUME_DIST": {
    "args": "",
    "description": "Returns the cumulative distribution of the current row within the window calculated as number of window rows at the same rank or higher than current row divided by total window rows. The return value ranges between `1/number of rows` and 1"
  },
  "CURRENT_DATE": {
    "args": "",
    "description": "Current date in UTC time, unless you specify a different timezone in the query context."
  },
  "CURRENT_TIMESTAMP": {
    "args": "",
    "description": "Current timestamp in UTC time, unless you specify a different timezone in the query context."
  },
  "DATE_TRUNC": {
    "args": "unit, timestamp_expr",
    "description": "Rounds down a timestamp, returning it as a new timestamp. Unit can be 'milliseconds', 'second', 'minute', 'hour', 'day', 'week', 'month', 'quarter', 'year', 'decade', 'century', or 'millennium'."
  },
  "DECODE_BASE64_COMPLEX": {
    "args": "dataType, expr",
    "description": "Decodes a Base64-encoded string into a complex data type, where `dataType` is the complex data type and `expr` is the Base64-encoded string to decode. The `hyperUnique` and `serializablePairLongString` data types are supported by default. You can enable support for the following complex data types by loading their extensions:\n<ul><li>`druid-bloom-filter`: `bloom`</li><li>`druid-datasketches`: `arrayOfDoublesSketch`, `HLLSketch`, `KllDoublesSketch`, `KllFloatsSketch`, `quantilesDoublesSketch`, `thetaSketch`</li><li>`druid-histogram`: `approximateHistogram`, `fixedBucketsHistogram`</li><li>`druid-stats`: `variance`</li><li>`druid-compressed-bigdecimal`: `compressedBigDecimal`</li><li>`druid-momentsketch`: `momentSketch`</li><li>`druid-tdigestsketch`: `tDigestSketch`</li></ul>"
  },
  "DECODE_BASE64_UTF8": {
    "args": "expr",
    "description": "Decodes a Base64-encoded string into a UTF-8 encoded string."
  },
  "DEGREES": {
    "args": "expr",
    "description": "Converts an angle measured in radians to an approximately equivalent angle measured in degrees."
  },
  "DENSE_RANK": {
    "args": "",
    "description": "Returns the rank for a row within a window without gaps. For example, if two rows tie for rank of 1, the subsequent row is ranked 2."
  },
  "DIV": {
    "args": "x, y",
    "description": "Returns the result of integer division of x by y"
  },
  "DS_CDF": {
    "args": "expr, splitPoint0, splitPoint1, ...",
    "description": "Returns a string representing approximation to the Cumulative Distribution Function given a list of split points that define the edges of the bins from a quantiles sketch. `expr` must return a quantiles sketch."
  },
  "DS_GET_QUANTILE": {
    "args": "expr, fraction",
    "description": "Returns the quantile estimate corresponding to `fraction` from a quantiles sketch. `expr` must return a quantiles sketch."
  },
  "DS_GET_QUANTILES": {
    "args": "expr, fraction0, fraction1, ...",
    "description": "Returns a string representing an array of quantile estimates corresponding to a list of fractions from a quantiles sketch. `expr` must return a quantiles sketch."
  },
  "DS_HISTOGRAM": {
    "args": "expr, splitPoint0, splitPoint1, ...",
    "description": "Returns a string representing an approximation to the histogram given a list of split points that define the histogram bins from a quantiles sketch. `expr` must return a quantiles sketch."
  },
  "DS_HLL": {
    "args": "expr, [lgK, tgtHllType]",
    "description": "Creates an HLL sketch on the values of `expr`, which can be a regular column or a column containing HLL sketches. The `lgK` and `tgtHllType` parameters are described in the HLL sketch documentation."
  },
  "DS_QUANTILE_SUMMARY": {
    "args": "expr",
    "description": "Returns a string summary of a quantiles sketch, useful for debugging. `expr` must return a quantiles sketch."
  },
  "DS_QUANTILES_SKETCH": {
    "args": "expr, [k]",
    "description": "Creates a Quantiles sketch on the values of `expr`, which can be a regular column or a column containing quantiles sketches. The `k` parameter is described in the Quantiles sketch documentation.\n\nSee the known issue with this function."
  },
  "DS_RANK": {
    "args": "expr, value",
    "description": "Returns an approximation to the rank of a given value that is the fraction of the distribution less than that value from a quantiles sketch. `expr` must return a quantiles sketch."
  },
  "DS_THETA": {
    "args": "expr, [size]",
    "description": "Creates a Theta sketch on the values of `expr`, which can be a regular column or a column containing Theta sketches. The `size` parameter is described in the Theta sketch documentation."
  },
  "DS_TUPLE_DOUBLES_INTERSECT": {
    "args": "expr, ...[, nominalEntries]",
    "description": "Returns an intersection of tuple sketches, where each input expression must return a tuple sketch which contains an array of double values as its Summary Object. The values contained in the Summary Objects are summed when combined. If the last value of the array is a numeric literal, Druid assumes that the value is an override parameter for nominal entries."
  },
  "DS_TUPLE_DOUBLES_NOT": {
    "args": "expr, ...[, nominalEntries]",
    "description": "Returns a set difference of tuple sketches, where each input expression must return a tuple sketch which contains an array of double values as its Summary Object. The values contained in the Summary Object are preserved as is. If the last value of the array is a numeric literal, Druid assumes that the value is an override parameter for nominal entries."
  },
  "DS_TUPLE_DOUBLES_UNION": {
    "args": "expr, ...[, nominalEntries]",
    "description": "Returns a union of tuple sketches, where each input expression must return a tuple sketch which contains an array of double values as its Summary Object. The values contained in the Summary Objects are summed when combined. If the last value of the array is a numeric literal, Druid assumes that the value is an override parameter for nominal entries."
  },
  "EARLIEST": {
    "args": "expr, [maxBytesPerValue]",
    "description": "Returns the earliest value of `expr`.\nIf `expr` comes from a relation with a timestamp column (like `__time` in a Druid datasource), the \"earliest\" is taken from the row with the overall earliest non-null value of the timestamp column.\nIf the earliest non-null value of the timestamp column appears in multiple rows, the `expr` may be taken from any of those rows. If `expr` does not come from a relation with a timestamp, then it is simply the first value encountered.\n\nIf `expr` is a string or complex type `maxBytesPerValue` amount of space is allocated for the aggregation. Strings longer than this limit are truncated. The  `maxBytesPerValue` parameter should be set as low as possible, since high values will lead to wasted memory.\nIf `maxBytesPerValue`is omitted; it defaults to `1024`."
  },
  "EARLIEST_BY": {
    "args": "expr, timestampExpr, [maxBytesPerValue]",
    "description": "Returns the earliest value of `expr`.\nThe earliest value of `expr` is taken from the row with the overall earliest non-null value of `timestampExpr`. \nIf the earliest non-null value of `timestampExpr` appears in multiple rows, the `expr` may be taken from any of those rows.\n\nIf `expr` is a string or complex type `maxBytesPerValue` amount of space is allocated for the aggregation. Strings longer than this limit are truncated. The  `maxBytesPerValue` parameter should be set as low as possible, since high values will lead to wasted memory.\nIf `maxBytesPerValue`is omitted; it defaults to `1024`.\n\nUse `EARLIEST` instead of `EARLIEST_BY` on a table that has rollup enabled and was created with any variant of `EARLIEST`, `LATEST`, `EARLIEST_BY`, or `LATEST_BY`. In these cases, the intermediate type already stores the timestamp, and Druid ignores the value passed in `timestampExpr`."
  },
  "EXP": {
    "args": "expr",
    "description": "e to the power of `expr`."
  },
  "EXTERN": {
    "args": "inputSource, inputFormat, rowSignature?",
    "description": "Reads external data."
  },
  "EXTRACT": {
    "args": "unit FROM timestamp_expr",
    "description": "Extracts a time part from `expr`, returning it as a number. Unit can be EPOCH, MILLISECOND, SECOND, MINUTE, HOUR, DAY (day of month), DOW (day of week), ISODOW (ISO day of week), DOY (day of year), WEEK (week of year), MONTH, QUARTER, YEAR, ISOYEAR, DECADE, CENTURY or MILLENNIUM. Units must be provided unquoted, like `EXTRACT(HOUR FROM __time)`."
  },
  "FIRST_VALUE": {
    "args": "expr",
    "description": "Returns the value evaluated for the expression for the first row within the window"
  },
  "FLOOR": {
    "args": "timestamp_expr TO unit",
    "description": "Rounds down a timestamp, returning it as a new timestamp. The `unit` parameter must be unquoted and can be SECOND, MINUTE, HOUR, DAY, WEEK, MONTH, QUARTER, or YEAR."
  },
  "GREATEST": {
    "args": "[expr1, ...]",
    "description": "Evaluates zero or more expressions and returns the maximum value based on comparisons as described above."
  },
  "GROUPING": {
    "args": "expr, expr...",
    "description": "Returns a number to indicate which groupBy dimension is included in a row, when using `GROUPING SETS`. Refer to additional documentation on how to infer this number."
  },
  "HLL_SKETCH_ESTIMATE": {
    "args": "expr[, round]",
    "description": "Returns a distinct count estimate from a HLL sketch. `expr` must be a HLL sketch. To round the estimate, set `round` to true. Otherwise, `round` defaults to false."
  },
  "HLL_SKETCH_ESTIMATE_WITH_ERROR_BOUNDS": {
    "args": "expr[, numStdDev]",
    "description": "Returns a distinct count estimate and error bounds from a HLL sketch. `expr` must be a HLL sketch. `numStdDev` argument specifies the number of standard deviations of the bounds. `numStdDev` must be `1`, `2`, or `3`."
  },
  "HLL_SKETCH_TO_STRING": {
    "args": "expr",
    "description": "Returns a human-readable string representation of an HLL sketch for debugging. `expr` must return an HLL sketch."
  },
  "HLL_SKETCH_UNION": {
    "args": "[lgK, tgtHllType], expr0, expr1, ...",
    "description": "Returns a union of HLL sketches, where each input expression must return an HLL sketch. The `lgK` and `tgtHllType` can be optionally specified as the first parameter; if provided, both optional parameters must be specified."
  },
  "HUMAN_READABLE_BINARY_BYTE_FORMAT": {
    "args": "value[, precision]",
    "description": "Formats a number in human-readable IEC format. For example, `HUMAN_READABLE_BINARY_BYTE_FORMAT(1048576)` returns `1.00 MiB`. `precision` must be in the range of `[0, 3]`. If not specified,  `precision` defaults to 2."
  },
  "HUMAN_READABLE_DECIMAL_BYTE_FORMAT": {
    "args": "value[, precision]",
    "description": "Formats a number in human-readable SI format. For example, `HUMAN_READABLE_DECIMAL_BYTE_FORMAT(1048576)` returns `1.04 MB`. `precision` must be in the range of `[0, 3]`. If not specified, `precision` defaults to 2."
  },
  "HUMAN_READABLE_DECIMAL_FORMAT": {
    "args": "value[, precision]",
    "description": "Formats a number in human-readable SI format. For example, `HUMAN_READABLE_DECIMAL_FORMAT(1048576)` returns `1.04 M`. `precision` must be in the range of `[0, 3]`. If not specified, `precision` defaults to 2."
  },
  "ICONTAINS_STRING": {
    "args": "expr, str",
    "description": "Returns true if the `str` is a substring of `expr`. The match is case-insensitive."
  },
  "IPV4_MATCH": {
    "args": "address, subnet",
    "description": "Returns true if the `address` belongs to the `subnet` literal, else false. If `address` is not a valid IPv4 address, then false is returned. This function is more efficient if `address` is an integer instead of a string."
  },
  "IPV4_PARSE": {
    "args": "address",
    "description": "Parses `address` into an IPv4 address stored as an integer . If `address` is an integer that is a valid IPv4 address, then it is passed through. Returns null if `address` cannot be represented as an IPv4 address."
  },
  "IPV4_STRINGIFY": {
    "args": "address",
    "description": "Converts `address` into an IPv4 address dotted-decimal string. If `address` is a string that is a valid IPv4 address, then it is passed through. Returns null if `address` cannot be represented as an IPv4 address."
  },
  "JSON_KEYS": {
    "args": "expr, path",
    "description": "Returns an array of field names from `expr` at the specified `path`."
  },
  "JSON_MERGE": {
    "args": "expr1, expr2[, expr3 ...]",
    "description": "Merges two or more JSON `STRING` or `COMPLEX<json>` values into one, preserving the rightmost value when there are key overlaps. Returns `NULL` if any argument is `NULL`. Always returns a `COMPLEX<json>` object."
  },
  "JSON_OBJECT": {
    "args": "KEY expr1 VALUE expr2[, KEY expr3 VALUE expr4, ...]",
    "description": "Constructs a new `COMPLEX<json>` object from one or more expressions. The `KEY` expressions must evaluate to string types. The `VALUE` expressions can be composed of any input type, including other `COMPLEX<json>` objects. The function can accept colon-separated key-value pairs. The following syntax is equivalent: `JSON_OBJECT(expr1:expr2[, expr3:expr4, ...])`."
  },
  "JSON_PATHS": {
    "args": "expr",
    "description": "Returns an array of all paths which refer to primitive values in `expr` in JSONPath format."
  },
  "JSON_QUERY": {
    "args": "expr, path",
    "description": "Extracts a `COMPLEX<json>` value from `expr`, at the specified `path`."
  },
  "JSON_QUERY_ARRAY": {
    "args": "expr, path",
    "description": "Extracts an `ARRAY<COMPLEX<json>>` value from `expr` at the specified `path`. If the value isn't an `ARRAY`, the function translates it into a single element `ARRAY` containing the value at `path`. Mainly used to extract arrays of objects to use as inputs to other array functions."
  },
  "JSON_VALUE": {
    "args": "expr, path [RETURNING sqlType]",
    "description": "Extracts a primitive value from `expr` at the specified `path`. If you include `RETURNING` and specify a SQL type (such as `VARCHAR`, `BIGINT`, `DOUBLE`) the function plans the query using the suggested type. If `RETURNING` isn't included, the function attempts to infer the type based on the context. If the function can't infer the type, it defaults to `VARCHAR`. Primitive arrays can also be returned, but only if `RETURNING` is specified as an `ARRAY` type, e.g. `RETURNING VARCHAR ARRAY`."
  },
  "LAG": {
    "args": "expr[, offset]",
    "description": "If you do not supply an `offset`, returns the value evaluated at the row preceding the current row. Specify an offset number, `n`, to return the value evaluated at `n` rows preceding the current one"
  },
  "LAST_VALUE": {
    "args": "expr",
    "description": "Returns the value evaluated for the expression for the last row within the window"
  },
  "LATEST": {
    "args": "expr, [maxBytesPerValue]",
    "description": "Returns the latest value of `expr`\nThe `expr` must come from a relation with a timestamp column (like `__time` in a Druid datasource) and the \"latest\" is taken from the row with the overall latest non-null value of the timestamp column.\nIf the latest non-null value of the timestamp column appears in multiple rows, the `expr` may be taken from any of those rows.\n\nIf `expr` is a string or complex type `maxBytesPerValue` amount of space is allocated for the aggregation. Strings longer than this limit are truncated. The  `maxBytesPerValue` parameter should be set as low as possible, since high values will lead to wasted memory.\nIf `maxBytesPerValue`is omitted; it defaults to `1024`."
  },
  "LATEST_BY": {
    "args": "expr, timestampExpr, [maxBytesPerValue]",
    "description": "Returns the latest value of `expr`.\nThe latest value of `expr` is taken from the row with the overall latest non-null value of `timestampExpr`.\nIf the overall latest non-null value of `timestampExpr` appears in multiple rows, the `expr` may be taken from any of those rows.\n\nIf `expr` is a string or complex type `maxBytesPerValue` amount of space is allocated for the aggregation. Strings longer than this limit are truncated. The `maxBytesPerValue` parameter should be set as low as possible, since high values will lead to wasted memory.\nIf `maxBytesPerValue`is omitted; it defaults to `1024`.\n\nUse `LATEST` instead of `LATEST_BY` on a table that has rollup enabled and was created with any variant of `EARLIEST`, `LATEST`, `EARLIEST_BY`, or `LATEST_BY`. In these cases, the intermediate type already stores the timestamp, and Druid ignores the value passed in `timestampExpr`."
  },
  "LEAD": {
    "args": "expr[, offset]",
    "description": "If you do not supply an `offset`, returns the value evaluated at the row following the current row. Specify an offset number `n` to return the value evaluated at `n` rows following the current one; if there is no such row, returns the given default value"
  },
  "LEAST": {
    "args": "[expr1, ...]",
    "description": "Evaluates zero or more expressions and returns the minimum value based on comparisons as described above."
  },
  "LEFT": {
    "args": "expr, N",
    "description": "Returns the `N` leftmost characters from `expr`, where `N` is an integer."
  },
  "LENGTH": {
    "args": "expr",
    "description": "Length of `expr` in UTF-16 code units."
  },
  "LISTAGG": {
    "args": "[DISTINCT] expr, [separator, [size]]",
    "description": "Synonym for `STRING_AGG`."
  },
  "LN": {
    "args": "expr",
    "description": "Logarithm (base e)."
  },
  "LOG10": {
    "args": "expr",
    "description": "Logarithm (base 10)."
  },
  "LOOKUP": {
    "args": "expr, lookupName[, replaceMissingValueWith]",
    "description": "Searches for `expr` in a registered query-time lookup table named `lookupName` and returns the mapped value. If `expr` is null or not contained in the lookup, returns `replaceMissingValueWith` if supplied, otherwise returns null.\n\nYou can query lookups directly using the `lookup` schema."
  },
  "LOWER": {
    "args": "expr",
    "description": "Returns `expr` in all lowercase."
  },
  "LPAD": {
    "args": "expr, length[, chars]",
    "description": "Returns a string of `length` from `expr`. If `expr` is shorter than `length`, left pads `expr` with `chars`, which defaults to space characters. If `expr` exceeds `length`, truncates `expr` to equal `length`.  If `chars` is an empty string, no padding is added. Returns `null` if either `expr` or `chars` is null."
  },
  "LTRIM": {
    "args": "expr[, chars]",
    "description": "Alternate form of `TRIM(LEADING chars FROM expr)`."
  },
  "MAX": {
    "args": "expr",
    "description": "Takes the maximum of numbers."
  },
  "MILLIS_TO_TIMESTAMP": {
    "args": "millis_expr",
    "description": "Converts a number of milliseconds since the epoch (1970-01-01 00:00:00 UTC) into a timestamp."
  },
  "MIN": {
    "args": "expr",
    "description": "Takes the minimum of numbers."
  },
  "MOD": {
    "args": "x, y",
    "description": "Modulo (remainder of x divided by y)."
  },
  "MV_APPEND": {
    "args": "arr, expr",
    "description": "Appends `expr` to `arr`, the resulting array type determined by the type of `arr`."
  },
  "MV_CONCAT": {
    "args": "arr1, arr2",
    "description": "Concatenates `arr2` to `arr1`. The resulting array type is determined by the type of `arr1`."
  },
  "MV_CONTAINS": {
    "args": "arr, expr",
    "description": "If `expr` is a scalar type, returns true if `arr` contains `expr`. If `expr` is an array, returns true if `arr` contains all elements of `expr`. Otherwise returns false."
  },
  "MV_FILTER_NONE": {
    "args": "expr, arr",
    "description": "Filters multi-value `expr` to include no values contained in array `arr`."
  },
  "MV_FILTER_ONLY": {
    "args": "expr, arr",
    "description": "Filters multi-value `expr` to include only values contained in array `arr`."
  },
  "MV_FILTER_PREFIX": {
    "args": "expr, prefix",
    "description": "Filters multi-value `expr` to include values that have prefix `prefix`."
  },
  "MV_FILTER_REGEX": {
    "args": "expr, pattern",
    "description": "Filters multi-value `expr` to include values that match `pattern`."
  },
  "MV_LENGTH": {
    "args": "arr",
    "description": "Returns length of the array expression."
  },
  "MV_OFFSET": {
    "args": "arr, long",
    "description": "Returns the array element at the 0-based index supplied, or null for an out of range index."
  },
  "MV_OFFSET_OF": {
    "args": "arr, expr",
    "description": "Returns the 0-based index of the first occurrence of `expr` in the array. If no matching elements exist in the array, returns `null`."
  },
  "MV_ORDINAL": {
    "args": "arr, long",
    "description": "Returns the array element at the 1-based index supplied, or null for an out of range index."
  },
  "MV_ORDINAL_OF": {
    "args": "arr, expr",
    "description": "Returns the 1-based index of the first occurrence of `expr` in the array. If no matching elements exist in the array, returns `null`."
  },
  "MV_OVERLAP": {
    "args": "arr1, arr2",
    "description": "Returns true if `arr1` and `arr2` have any elements in common, else false."
  },
  "MV_PREPEND": {
    "args": "expr, arr",
    "description": "Adds `expr` to the beginning of `arr`, the resulting array type determined by the type `arr`."
  },
  "MV_SLICE": {
    "args": "arr, start, end",
    "description": "Returns the subarray of `arr` from the zero-based index of `start` (inclusive) to `end` (exclusive). Returns null when `start` is less than 0, greater than the array length, or greater than `end`. When `end` is greater than the array length, null values are appended to the subarray."
  },
  "MV_TO_ARRAY": {
    "args": "str",
    "description": "Converts a multi-value string from a `VARCHAR` to a `VARCHAR ARRAY`."
  },
  "MV_TO_STRING": {
    "args": "arr, str",
    "description": "Joins all elements of `arr` by the delimiter specified by `str`."
  },
  "NTILE": {
    "args": "tiles",
    "description": "Divides the rows within a window as evenly as possible into the number of tiles, also called buckets, and returns the value of the tile that the row falls into"
  },
  "NULLIF": {
    "args": "value1, value2",
    "description": "Returns NULL if `value1` and `value2` match, else returns `value1`."
  },
  "NVL": {
    "args": "value1, value2",
    "description": "Returns `value1` if `value1` is not null, otherwise `value2`."
  },
  "PARSE_JSON": {
    "args": "expr",
    "description": "Parses `expr` into a `COMPLEX<json>` object. This function deserializes JSON values when processing them, translating stringified JSON into a nested structure. If the input is invalid JSON or not a `VARCHAR`, it returns an error."
  },
  "PARSE_LONG": {
    "args": "string[, radix]",
    "description": "Parses a string into a long (BIGINT) with the given radix, or 10 (decimal) if a radix is not provided."
  },
  "PERCENT_RANK": {
    "args": "",
    "description": "Returns the relative rank of the row calculated as a percentage according to the formula: `RANK() OVER (window) / COUNT(1) OVER (window)`"
  },
  "PI": {
    "args": "",
    "description": "Constant Pi."
  },
  "POSITION": {
    "args": "substring IN expr [FROM startingIndex]",
    "description": "Returns the index of `substring` within `expr` with indexes starting from 1. The search begins at `startingIndex`. If `startingIndex` is not specified, the default is 1. If `substring` is not found, returns 0."
  },
  "POWER": {
    "args": "expr, power",
    "description": "`expr` raised to the power of `power`."
  },
  "RADIANS": {
    "args": "expr",
    "description": "Converts an angle measured in degrees to an approximately equivalent angle measured in radians."
  },
  "REGEXP_EXTRACT": {
    "args": "expr, pattern[, index]",
    "description": "Apply regular expression `pattern` to `expr` and extract a capture group or `NULL` if there is no match. If `index` is unspecified or zero, returns the first substring that matches the pattern. The pattern may match anywhere inside `expr`. To match the entire string, use the `^` and `$` markers at the start and end of your pattern."
  },
  "REGEXP_LIKE": {
    "args": "expr, pattern",
    "description": "Returns whether `expr` matches regular expression `pattern`. The pattern may match anywhere inside `expr`; if you want to match the entire string instead, use the `^` and `$` markers at the start and end of your pattern. Similar to `LIKE`, but uses regexps instead of LIKE patterns. Especially useful in WHERE clauses."
  },
  "REGEXP_REPLACE": {
    "args": "expr, pattern, replacement",
    "description": "Replaces all occurrences of regular expression `pattern` within `expr` with `replacement`. The replacement string may refer to capture groups using `$1`, `$2`, etc. The pattern may match anywhere inside `expr`; if you want to match the entire string instead, use the `^` and `$` markers at the start and end of your pattern."
  },
  "REPEAT": {
    "args": "expr, N",
    "description": "Repeats `expr` `N` times."
  },
  "REPLACE": {
    "args": "expr, substring, replacement",
    "description": "Replaces instances of `substring` in `expr` with `replacement` and returns the result."
  },
  "REVERSE": {
    "args": "expr",
    "description": "Reverses `expr`."
  },
  "RIGHT": {
    "args": "expr, N",
    "description": "Returns the `N` rightmost characters from `expr`, where `N` is an integer."
  },
  "ROUND": {
    "args": "expr[, digits]",
    "description": "Rounds `expr` to a specific number of decimal digits. If `digits` is negative, then it rounds that many places to the left of the decimal point. If not specified, `digits` defaults to zero."
  },
  "ROW_NUMBER": {
    "args": "",
    "description": "Returns the number of the row within the window starting from 1"
  },
  "RPAD": {
    "args": "expr, length[, chars]",
    "description": "Returns a string of `length` from `expr`. If `expr` is shorter than `length`, right pads `expr` with `chars`, which defaults to space characters. If `expr` exceeds `length`, truncates `expr` to equal `length`.  If `chars` is an empty string, no padding is added. Returns `null` if either `expr` or `chars` is null."
  },
  "RTRIM": {
    "args": "expr[, chars]",
    "description": "Alternate form of `TRIM(TRAILING chars FROM expr)`."
  },
  "SAFE_DIVIDE": {
    "args": "x, y",
    "description": "Returns the division of x by y guarded on division by 0. In case y is 0 it returns `null`"
  },
  "SCALAR_IN_ARRAY": {
    "args": "expr, arr",
    "description": "Checks if the scalar value is present in the array. Returns false if the value is non-null, or `UNKNOWN` if the value is `NULL`. Returns `UNKNOWN` if the array is `NULL`."
  },
  "SIN": {
    "args": "expr",
    "description": "Trigonometric sine of an angle `expr`."
  },
  "SPECTATOR_COUNT": {
    "args": "expr",
    "description": "Counts the total number of observations (data points) in a Spectator histogram. The `expr` can be either a numeric column (which will be aggregated into a histogram) or a pre-aggregated Spectator histogram column."
  },
  "SPECTATOR_PERCENTILE": {
    "args": "expr, ARRAY[p1, p2, ...]",
    "description": "Computes multiple approximate percentile values from a Spectator histogram and returns them as a DOUBLE ARRAY. The `expr` can be either a numeric column (which will be aggregated into a histogram) or a pre-aggregated Spectator histogram column. Each percentile value in the array should be between 0 and 100. This is more efficient than calling `SPECTATOR_PERCENTILE` multiple times for different percentiles."
  },
  "SQRT": {
    "args": "expr",
    "description": "Square root."
  },
  "STDDEV": {
    "args": "expr",
    "description": "Computes standard deviation sample of `expr`. See stats extension documentation for additional details."
  },
  "STDDEV_POP": {
    "args": "expr",
    "description": "Computes standard deviation population of `expr`. See stats extension documentation for additional details."
  },
  "STDDEV_SAMP": {
    "args": "expr",
    "description": "Computes standard deviation sample of `expr`. See stats extension documentation for additional details."
  },
  "STRING_AGG": {
    "args": "[DISTINCT] expr, [separator, [size]]",
    "description": "Collects all values (or all distinct values) of `expr` into a single STRING, ignoring null values. Each value is joined by an optional `separator`, which must be a literal STRING. If the `separator` is not provided, strings are concatenated without a separator.\n\nAn optional `size` in bytes can be supplied to limit aggregation size (default of 1024 bytes). If the aggregated string grows larger than the maximum size in bytes, the query will fail. Use of `ORDER BY` within the `STRING_AGG` expression is not currently supported, and the ordering of results within the output string may vary depending on processing order."
  },
  "STRING_FORMAT": {
    "args": "pattern[, args...]",
    "description": "Returns a string formatted in the manner of Java's String.format)."
  },
  "STRING_TO_ARRAY": {
    "args": "string, delimiter",
    "description": "Splits the string into an array of substrings using the specified delimiter. The delimiter must be a valid regular expression."
  },
  "STRING_TO_MV": {
    "args": "str1, str2",
    "description": "Splits `str1` into an array on the delimiter specified by `str2`, which is a regular expression."
  },
  "STRLEN": {
    "args": "expr",
    "description": "Alias for `LENGTH`."
  },
  "STRPOS": {
    "args": "expr, substring",
    "description": "Returns the index of `substring` within `expr`, with indexes starting from 1. If `substring` is not found, returns 0."
  },
  "SUBSTR": {
    "args": "expr, index[, length]",
    "description": "Alias for `SUBSTRING`."
  },
  "SUBSTRING": {
    "args": "expr, index[, length]",
    "description": "Returns a substring of `expr` starting at a given one-based index. If `length` is omitted, extracts characters to the end of the string, otherwise returns a substring of `length` UTF-16 characters."
  },
  "SUM": {
    "args": "expr",
    "description": "Sums numbers."
  },
  "TABLE": {
    "args": "external",
    "description": "Defines a logical table from an external."
  },
  "TAN": {
    "args": "expr",
    "description": "Trigonometric tangent of an angle `expr`."
  },
  "TDIGEST_GENERATE_SKETCH": {
    "args": "expr, [compression]",
    "description": "Builds a T-Digest sketch on values produced by `expr`. Compression parameter (default value 100) determines the accuracy and size of the sketch Higher compression means higher accuracy but more space to store sketches."
  },
  "TDIGEST_QUANTILE": {
    "args": "expr, quantileFraction, [compression]",
    "description": "Builds a T-Digest sketch on values produced by `expr` and returns the value for the quantile. Compression parameter (default value 100) determines the accuracy and size of the sketch. Higher compression means higher accuracy but more space to store sketches."
  },
  "TEXTCAT": {
    "args": "expr, expr",
    "description": "Concatenates two expressions."
  },
  "THETA_SKETCH_ESTIMATE": {
    "args": "expr",
    "description": "Returns the distinct count estimate from a theta sketch. `expr` must return a theta sketch."
  },
  "THETA_SKETCH_ESTIMATE_WITH_ERROR_BOUNDS": {
    "args": "expr, errorBoundsStdDev",
    "description": "Returns the distinct count estimate and error bounds from a theta sketch. `expr` must return a theta sketch."
  },
  "THETA_SKETCH_INTERSECT": {
    "args": "[size], expr0, expr1, ...",
    "description": "Returns an intersection of theta sketches, where each input expression must return a theta sketch. The `size` can be optionally specified as the first parameter."
  },
  "THETA_SKETCH_NOT": {
    "args": "[size], expr0, expr1, ...",
    "description": "Returns a set difference of theta sketches, where each input expression must return a theta sketch. The `size` can be optionally specified as the first parameter."
  },
  "THETA_SKETCH_UNION": {
    "args": "[size], expr0, expr1, ...",
    "description": "Returns a union of theta sketches, where each input expression must return a theta sketch. The `size` can be optionally specified as the first parameter."
  },
  "TIME_CEIL": {
    "args": "timestamp_expr, period[, origin[, timezone]]",
    "description": "Rounds up a timestamp, returning it as a new timestamp. Period can be any ISO 8601 period, like P3M (quarters) or PT12H (half-days). Specify `origin` as a timestamp to set the reference time for rounding. For example, `TIME_CEIL(__time, 'PT1H', TIMESTAMP '2016-06-27 00:30:00')` measures an hourly period from 00:30-01:30 instead of 00:00-01:00. See Period granularities for details on the default starting boundaries. The time zone, if provided, should be a time zone name like `America/Los_Angeles` or an offset like `-08:00`. This function is similar to `CEIL` but is more flexible."
  },
  "TIME_EXTRACT": {
    "args": "timestamp_expr, unit[, timezone]",
    "description": "Extracts a time part from `expr`, returning it as a number. Unit can be EPOCH, MILLISECOND, SECOND, MINUTE, HOUR, DAY (day of month), DOW (day of week), DOY (day of year), WEEK (week of week year), MONTH (1 through 12), QUARTER (1 through 4), or YEAR. The time zone, if provided, should be a time zone name like `America/Los_Angeles` or an offset like `-08:00`. The `unit` and `timezone` parameters must be provided as quoted literals, such as `TIME_EXTRACT(__time, 'HOUR')` or `TIME_EXTRACT(__time, 'HOUR', 'America/Los_Angeles')`. This function is similar to `EXTRACT` but is more flexible."
  },
  "TIME_FLOOR": {
    "args": "timestamp_expr, period[, origin[, timezone]]",
    "description": "Rounds down a timestamp, returning it as a new timestamp. Period can be any ISO 8601 period, like P3M (quarters) or PT12H (half-days). Specify `origin` as a timestamp to set the reference time for rounding. For example, `TIME_FLOOR(__time, 'PT1H', TIMESTAMP '2016-06-27 00:30:00')` measures an hourly period from 00:30-01:30 instead of 00:00-01:00. See Period granularities for details on the default starting boundaries. The time zone, if provided, should be a time zone name like `America/Los_Angeles` or an offset like `-08:00`. This function is similar to `FLOOR` but is more flexible."
  },
  "TIME_FORMAT": {
    "args": "timestamp_expr[, pattern[, timezone]]",
    "description": "Formats a timestamp as a string with a given Joda DateTimeFormat pattern, or ISO 8601 (e.g. `2000-01-02T03:04:05Z`) if the pattern is not provided. If provided, the `timezone` parameter should be a time zone name like `America/Los_Angeles` or an offset like `-08:00`. The `pattern` and `timezone` parameters must be literals."
  },
  "TIME_IN_INTERVAL": {
    "args": "timestamp_expr, interval",
    "description": "Returns whether a timestamp is contained within a particular interval. The interval must be a literal string containing any ISO 8601 interval, such as `'2001-01-01/P1D'` or `'2001-01-01T01:00:00/2001-01-02T01:00:00'`. The start instant of the interval is inclusive and the end instant is exclusive."
  },
  "TIME_PARSE": {
    "args": "string_expr[, pattern[, timezone]]",
    "description": "Parses a string into a timestamp using a given Joda DateTimeFormat pattern, or ISO 8601 (e.g. `2000-01-02T03:04:05Z`) if the pattern is not provided. The `timezone` parameter is used as the time zone for strings that do not already include a time zone offset. If provided, `timezone` should be a time zone name like `America/Los_Angeles` or an offset like `-08:00`. The `pattern` and `timezone` parameters must be literals. Strings that cannot be parsed as timestamps return NULL."
  },
  "TIME_SHIFT": {
    "args": "timestamp_expr, period, step[, timezone]",
    "description": "Shifts a timestamp by a period (step times), returning it as a new timestamp. The `period` parameter can be any ISO 8601 period. The `step` parameter can be negative. The time zone, if provided, should be a time zone name like `America/Los_Angeles` or an offset like `-08:00`."
  },
  "TIMESTAMP_TO_MILLIS": {
    "args": "timestamp_expr",
    "description": "Converts a timestamp into a number of milliseconds since the epoch."
  },
  "TIMESTAMPADD": {
    "args": "unit, count, timestamp",
    "description": "Adds a `count` number of time `unit` to timestamp, equivalent to `timestamp + count * unit`. The `unit` parameter must be unquoted and can be SECOND, MINUTE, HOUR, DAY, WEEK, MONTH, QUARTER, or YEAR."
  },
  "TIMESTAMPDIFF": {
    "args": "unit, timestamp1, timestamp2",
    "description": "Returns a signed number of `unit` between `timestamp1` and `timestamp2`. The `unit` parameter must be unquoted and can be SECOND, MINUTE, HOUR, DAY, WEEK, MONTH, QUARTER, or YEAR."
  },
  "TO_JSON_STRING": {
    "args": "expr",
    "description": "Serializes `expr` into a JSON string."
  },
  "TRIM": {
    "args": "[BOTH | LEADING | TRAILING] [chars FROM] expr",
    "description": "Returns `expr` with characters removed from the leading, trailing, or both ends of `expr` if they are in `chars`. If `chars` is not provided, it defaults to `''` (a space). If the directional argument is not provided, it defaults to `BOTH`."
  },
  "TRUNC": {
    "args": "expr[, digits]",
    "description": "Alias for `TRUNCATE`."
  },
  "TRUNCATE": {
    "args": "expr[, digits]",
    "description": "Truncates `expr` to a specific number of decimal digits. If `digits` is negative, then this truncates that many places to the left of the decimal point. If not specified, `digits` defaults to zero."
  },
  "TRY_PARSE_JSON": {
    "args": "expr",
    "description": "Parses `expr` into a `COMPLEX<json>` object. This operator deserializes JSON values when processing them, translating stringified JSON into a nested structure. If the input is invalid JSON or not a `VARCHAR`, it returns a `NULL` value."
  },
  "TYPE": {
    "args": "nativeType",
    "description": "A purely type system modification function what wraps a Druid native type to make it into a SQL type."
  },
  "UNNEST": {
    "args": "arrayExpression",
    "description": "Unnests ARRAY typed values. The source for UNNEST can be an array type column, or an input that's been transformed into an array, such as with helper functions like `MV_TO_ARRAY` or `ARRAY`."
  },
  "UPPER": {
    "args": "expr",
    "description": "Returns `expr` in all uppercase."
  },
  "VAR_POP": {
    "args": "expr",
    "description": "Computes variance population of `expr`. See stats extension documentation for additional details."
  },
  "VAR_SAMP": {
    "args": "expr",
    "description": "Computes variance sample of `expr`. See stats extension documentation for additional details."
  },
  "VARIANCE": {
    "args": "expr",
    "description": "Computes variance sample of `expr`. See stats extension documentation for additional details."
  }
};

export const SQL_DATA_TYPES: Record<string, SqlDataTypeDoc> = {
  "ARRAY": {
    "runtime": "ARRAY",
    "description": "Druid native array types work as SQL arrays, and multi-value strings can be converted to arrays. See Arrays for more information."
  },
  "BIGINT": {
    "runtime": "LONG",
    "description": "Druid LONG columns (except `__time`) are reported as BIGINT"
  },
  "BOOLEAN": {
    "runtime": "LONG",
    "description": ""
  },
  "CHAR": {
    "runtime": "STRING",
    "description": ""
  },
  "DATE": {
    "runtime": "LONG",
    "description": "Casting TIMESTAMP to DATE rounds down the timestamp to the nearest day. Casts between string and date types assume standard SQL formatting&mdash;for example, `2000-01-02`. For handling other formats, use one of the time functions."
  },
  "DECIMAL": {
    "runtime": "DOUBLE",
    "description": "DECIMAL uses floating point, not fixed point math"
  },
  "DOUBLE": {
    "runtime": "DOUBLE",
    "description": "Druid DOUBLE columns are reported as DOUBLE"
  },
  "FLOAT": {
    "runtime": "FLOAT",
    "description": "Druid FLOAT columns are reported as FLOAT"
  },
  "INTEGER": {
    "runtime": "LONG",
    "description": ""
  },
  "OTHER": {
    "runtime": "COMPLEX",
    "description": "May represent various Druid column types such as hyperUnique, approxHistogram, etc."
  },
  "REAL": {
    "runtime": "DOUBLE",
    "description": ""
  },
  "SMALLINT": {
    "runtime": "LONG",
    "description": ""
  },
  "TIMESTAMP": {
    "runtime": "LONG",
    "description": "Druid's `__time` column is reported as TIMESTAMP. Casts between string and timestamp types assume standard SQL formatting, such as `2000-01-02 03:04:05`, not ISO 8601 formatting. For handling other formats, use one of the time functions."
  },
  "TINYINT": {
    "runtime": "LONG",
    "description": ""
  },
  "VARCHAR": {
    "runtime": "STRING",
    "description": "Druid STRING columns are reported as VARCHAR. Can include multi-value strings as well."
  }
};
