// Vendored from Apache Druid's web-console/lib/keywords.ts
// (https://github.com/apache/druid, Apache License 2.0). Hand-curated upstream for
// Druid SQL and changes rarely, so it is vendored verbatim rather than generated.

export const SQL_KEYWORDS = [
  'ALL',
  'AND',
  'ANY',
  'AS',
  'ASC',
  'BETWEEN',
  'BOTH',
  'CASE',
  'CENTURY',
  'CLUSTERED BY',
  'CROSS',
  'CSV',
  'CUBE',
  'CURRENT',
  'DAY',
  'DAYS',
  'DECADE',
  'DESC',
  'DISTINCT',
  'DOW',
  'DOY',
  'ELSE',
  'END',
  'EPOCH',
  'ESCAPE',
  'EXPLAIN PLAN FOR',
  'EXTEND',
  'FETCH',
  'FILTER',
  'FIRST',
  'FOLLOWING',
  'FROM',
  'FULL',
  'GROUP BY',
  'GROUPING SETS',
  'HAVING',
  'HOUR',
  'HOURS',
  'IN',
  'INNER',
  'INSERT INTO',
  'INTERVAL',
  'IS',
  'ISODOW',
  'ISOYEAR',
  'JOIN',
  'KEY',
  'LEADING',
  'LEFT',
  'LIKE',
  'LIMIT',
  'MATCHED',
  'MERGE INTO',
  'MILLENNIUM',
  'MILLISECOND',
  'MINUTE',
  'MINUTES',
  'MONTH',
  'MONTHS',
  'NATURAL',
  'NEXT',
  'NOT',
  'OFFSET',
  'ON',
  'ONLY',
  'OR',
  'ORDER BY',
  'OUTER',
  'OVER',
  'OVERWRITE',
  'PARTITION BY',
  'PARTITIONED BY',
  'PIVOT',
  'PRECEDING',
  'QUARTER',
  'QUARTERS',
  'RANGE',
  'REPLACE INTO',
  'RETURNING',
  'RIGHT',
  'ROLLUP',
  'ROW',
  'ROWS',
  'SECOND',
  'SECONDS',
  'SELECT',
  'SET',
  'SIMILAR',
  'SOME',
  'SYMMETRIC',
  'THEN',
  'TIME',
  'TIMESTAMP',
  'TO',
  'TRAILING',
  'UNBOUNDED',
  'UNION ALL',
  'UNPIVOT',
  'UPDATE SET',
  'USING',
  'VALUE',
  'VALUES',
  'WEEK',
  'WEEKS',
  'WHEN',
  'WHERE',
  'WINDOW',
  'WITH',
  'YEAR',
  'YEARS',
];

export const SQL_CONSTANTS = ['NULL', 'FALSE', 'TRUE'];

// Short descriptions for SQL-standard vocabulary that Apache Druid's function docs do not list, so
// the generated catalog cannot supply them. Without these the completion widget shows an empty help
// pane for these entries. Hand-written (like the lists above), deliberately generic where Druid does
// not specify behaviour.
export const SQL_VOCABULARY_DOCS: Record<string, string> = {
  CURRENT_TIME: 'Current time in UTC time, unless you specify a different timezone in the query context.',
  LOCALTIME: 'Current time without time zone (SQL standard).',
  LOCALTIMESTAMP: 'Current timestamp without time zone (SQL standard).',
  NULL: 'The SQL null literal. Test for it with `IS NULL` / `IS NOT NULL`.',
  TRUE: 'Boolean true literal.',
  FALSE: 'Boolean false literal.',
};

export const SQL_DYNAMICS = ['CURRENT_TIMESTAMP', 'CURRENT_DATE', 'LOCALTIME', 'LOCALTIMESTAMP', 'CURRENT_TIME'];
