---
apiVersion: 1

datasources:
  - name: Druid
    type: grafadruid-druid-datasource
    access: proxy
    org_id: 1
    jsonData:
      connection.url: http://router:8888
    isDefault: true
    version: 1
    editable: true
